version: '3.7'

services:
  my-react-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
      - '/app/node_modules'
